<?php
$images=$this->getAllImages();
$media_path=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
?>
<div class="slider-wrapper">
<div id="nivo-slider" class="nivoSlider">
<?php foreach($images as $image): ?>
	<a href="<?php echo $image->getLink() ?>"><img src="<?php echo $media_path . $image->getPath()?>" alt="<?php echo $image->getName() ?>"></a>
<?php endforeach; ?>
</div>
</div>
<script type="text/javascript">
<?php echo $this->startJs(); ?>
</script>
